### ISSUE TITLE
Doubt about Color Scheme 

### ISSUE THREAD

**Issue by h3ct0rjs** [langner/lfm#1]
Hi @langner , 
Hope you're very well in this time, actually I'm testing your awesome file manager I'm running Debian Gnu/Linux as OS 64 bit I would like just to ask you about the color scheme, I can't figure it out How to change the background and foreground Color, I would like to have something like my color scheme of my music player http://imgur.com/JgRxpaG I've  changed the default color scheme but It seems no to work, How could I do something like in the picture, What would be the best approach to do this.

Thanks in advanced, 
a Happy new user of lfm.
Hector

**Comment by langner** [comment]
Hi. This is not _my_ file manager, I just uploaded the sources to GitHub for my own use.

However, you can read about the color themes at https://inigo.katxi.org/devel/lfm/#color-themes

**Comment by h3ct0rjs** [comment]
Hi Langner, Yeah the lead developer is called Iñigo Serna inigoserna@gmail.com he answer my question:

> I presume you are using old version 2.3.
> Upgrade to lfm version 3.x and you will be able to create your own theme and customize every colour (among many other new features).
> More info on https://inigo.katxi.org/devel/lfm/#color-themes
> But note it needs python 3.4 or upper, don't know if it's packaged and available for Debian.
> 
> Best regards,
> Iñigo Serna
